### ISSUE TITLE
Get rid of jquery-ui dependency

### ISSUE THREAD

**Issue by vladimir-e** [antonzaytsev/elrte-rails#5]
Hi. I'm having a problem using jquery-ui-rails gem and elrte-rails together.

`elrte-rails` includes default `jquery-ui.js` shipped with `jquery-rails` gem, but `jquery-ui-rails` uses own build of ui (few versions ahead). So when you use both gems you have jquery ui lib included twice.

It turns out that some ui components such as autocomplete don't work properly because of that.

I suggest to switch to `jquery-ui-rails` gem instead of relying on `jquery-rails`. What do you think?

\+ authors of `jquery-rails` reccomend to use ui gem
    For jQuery UI, we recommend the jquery-ui-rails gem, as it includes the jquery-ui css and allows easier customization. This gem still packages the jQuery UI javascript for compatibility.

\+ frequent updates

\- another dependency

**Comment by vladimir-e** [comment]
Sorry, I just found 2de5dbc8ee331f1cdc696e267c20a9f167ae3b30 :)

**Comment by antonzaytsev** [comment]
Thank you for your opened issue, I pushed new gem version on rubygems with latest fixes
